### ISSUE TITLE
Mongoose connects to MongoLab DB but cannot read data (Auth Error)

### ISSUE THREAD

**Issue by impactmass** [mongolab/mongodb-uri-node#2]
I set up my config like this:

```
var config = {
  "scheme": "mongodb",
  "hosts": [
    {
      "host": "ds1111-a1.mongolab.com",
      "port": 1234
    }
  ],
  "username": "user:n@me",
  "password": "p@ssword",
  "options": {
    "authSource": "@dmin"
  },
  "database": "d@tabase"
}
```

Then: 

```
var uriUtil = require('mongodb-uri');
var mongodbUri = uriUtil.format(config);
var mongooseUri = uriUtil.formatMongoose(mongodbUri);
mongoose.connect(mongooseUri);
```

The app connects to the db successfully, but when I make a query, I get this error: `'MongoError: not authorized for query on 'dbname.coll'`

Since it's pointing to auth, I tried with the username and password in the options, but I still get same error.

Any ideas on what's causing this?

**Comment by jcottr** [comment]
Since it looks like you're using a MongoLab deployment, you should start from the URI given in the MongoLab UI. You can find it using these instructions:

http://docs.mongolab.com/connecting/#connect-string

Be sure to fill in the `<dbuser>` and `<dbpassword>` placeholders with their actual values. Then feed it into `formatMongoose()`:

``` javascript
var uriUtil = require('mongodb-uri');
var standardUri = "mongodb://copied:and@pasted/from/mongolab/ui";
var mongooseUri = uriUtil.formatMongoose(standardUri);
mongoose.connect(mongooseUri);
```

Finally, some modern versions of Mongoose do accept the standard URI so you might check the docs and try that directly if supported.

PS - support@mongolab.com is a more expeditious method of getting support for your MongoLab-hosted deployment.
